import { BRAND_NAME, VERSION, type BriefDraft, type SelectionRecord } from './types';
import { createPanelHost } from '../panel/panel'; import { createOverlay, positionOverlay } from './overlay'; import { resolveTarget } from './target-resolver'; import { getAccessibleLabel,getLocator,getRegion,getVisualSummary,capturePageContext } from './context'; import { generateSelector } from './selector'; import { sanitizeElementHtml,truncateText } from './sanitizer'; import { generateBriefMarkdown,serializeBriefJson } from './prompt'; import { copyText,downloadText } from './clipboard'; import { detectLanguage,t } from './i18n';
import { loadPreferences, savePreferences } from './storage'; import { clampPanelPosition } from '../panel/position';
import { captureVideoRegion, prepareCaptureVideo, requestDisplayStream, selectCaptureRect } from './screenshot';
import { requestAiEnhancement } from './ai-bridge';
import { createFormState } from './form-state';

(() => {
  if (window.__PATCHBRIEF__) { window.__PATCHBRIEF__.open(); return; }
  const bridgeConfig=window.__PATCHBRIEF_AI_BRIDGE__;delete window.__PATCHBRIEF_AI_BRIDGE__;const preferences=loadPreferences();const language=preferences.language||detectLanguage(); const {host,root}=createPanelHost(); const hover=createOverlay('hover'); const selectedLayers:HTMLElement[]=[]; let paused=false; let collapsed=preferences.collapsed; let preview='';let aiMessage=''; let raf=0; let last:Element|null=null; let selections:SelectionRecord[]=[]; let history:SelectionRecord[][]=[]; let id=0;let drag:{pointerId:number;offsetX:number;offsetY:number;handle:HTMLElement}|null=null;let capturing=false;let activeCapture:ReturnType<typeof selectCaptureRect>|null=null;let captureStream:MediaStream|undefined;let screenshot:{blob:Blob;url:string;filename:string;width:number;height:number}|undefined;let screenshotMessage='';
  const formState=createFormState(preferences.defaultConstraints);
  const constraints=['不修改共享组件','不要安装新依赖','不修改无关文件','保持响应式兼容','保持现有交互','保持可访问性','先展示修改方案','修改后运行检查'];
  function record(el:Element):SelectionRecord{const r=el.getBoundingClientRect();return{id:`pb-${++id}`,element:el,label:getAccessibleLabel(el),tag:el.tagName.toLowerCase(),text:truncateText(el.textContent||''),selector:generateSelector(el),locator:getLocator(el),region:getRegion(el),rect:{x:r.x,y:r.y,width:r.width,height:r.height},visual:getVisualSummary(el),html:sanitizeElementHtml(el),note:''}}
  function save(){history.push([...selections]);if(history.length>30)history.shift()}
  function draft():BriefDraft{return{version:VERSION,page:capturePageContext(),selections:selections.map((s,i)=>({index:i+1,label:s.label,tag:s.tag,text:s.text,selector:s.selector,locator:s.locator,region:s.region,visual:s.visual,html:s.html,note:s.note,invalid:!s.element.isConnected})),request:formState.request,relatedCode:formState.code?{language:formState.language,content:formState.code}:undefined,constraints:[...formState.constraints],screenshot:screenshot?{filename:screenshot.filename,description:formState.screenshotNote.trim()||`用户手动框选的页面区域（${screenshot.width} × ${screenshot.height}）`}:undefined}}
  async function generate(){const useAi=formState.aiOptimize;const localBrief=generateBriefMarkdown(draft());aiMessage='';if(!useAi){preview=localBrief;render();return}const button=root.querySelector<HTMLButtonElement>('[data-action=generate]');if(button){button.disabled=true;button.textContent='AI 正在优化…'}try{preview=await requestAiEnhancement(localBrief,bridgeConfig);aiMessage='✓ 已使用 AI 优化，请检查内容后再复制。'}catch(error){preview=localBrief;aiMessage=`AI 优化失败，已保留本地任务书：${error instanceof Error?error.message:'未知错误'}`}render()}
  function applyPanelPosition(){const panel=root.querySelector<HTMLElement>('.panel');if(!panel)return;if(innerWidth<=620||!preferences.panelPosition){panel.style.left='';panel.style.right='';panel.style.top='';return}const bounded=clampPanelPosition(preferences.panelPosition,{width:innerWidth,height:innerHeight},{width:panel.offsetWidth,height:panel.offsetHeight});preferences.panelPosition=bounded;panel.style.left=`${bounded.x}px`;panel.style.top=`${bounded.y}px`;panel.style.right='auto'}
  function render(){selectedLayers.forEach(x=>x.remove());selectedLayers.length=0;selections.forEach(s=>{const x=createOverlay('selected');selectedLayers.push(x);positionOverlay(x,s.element)});const cards=selections.map((s,i)=>`<article class="target"><header><span class="badge">${i+1}</span><span>${escapeHtml(s.label)}</span><button class="remove" data-remove="${i}" title="Remove">×</button></header><div class="meta">${s.tag}${s.selector?` · ${escapeHtml(s.selector)}`:''}</div>${!s.element.isConnected?`<div class="invalid">${t(language,'invalid')}</div>`:''}<textarea data-note="${i}" placeholder="这个元素需要如何修改？">${escapeHtml(s.note||'')}</textarea></article>`).join('');root.querySelector('.panel')?.remove();const panel=document.createElement('section');panel.className=`panel${collapsed?' collapsed':''}`;panel.innerHTML=`<header class="top"><span class="brand">${BRAND_NAME}</span><span class="status">${paused?t(language,'pause'):'Inspecting'}</span><button class="icon" data-action="reset-position" title="恢复默认位置">⌂</button><button class="icon" data-action="pause">${paused?'▶':'Ⅱ'}</button><button class="icon" data-action="collapse">—</button><button class="icon" data-action="close">×</button></header><nav class="steps"><span>1 ${t(language,'select')}</span><span>2 ${t(language,'describe')}</span><span>3 ${t(language,'code')}</span><span>4 ${t(language,'generate')}</span></nav><main class="body">${preview?`${aiMessage?`<div class="ai-message">${escapeHtml(aiMessage)}</div>`:'' }<div class="preview">${escapeHtml(preview)}</div>`:`<div class="targets">${cards||`<div class="empty">${t(language,'empty')}</div>`}</div><label>全局修改目标</label><textarea name="request" placeholder="描述希望发生的变化"></textarea><label>相关代码</label><div class="row"><select name="language">${['TSX','JSX','TypeScript','JavaScript','Vue','HTML','CSS','SCSS','Other'].map(x=>`<option>${x}</option>`).join('')}</select><span class="count">0 chars</span><button class="icon" data-action="clear-code">清空</button></div><textarea class="code" name="code" spellcheck="false"></textarea><label>修改约束</label><div class="checks">${constraints.map(x=>`<label><input type="checkbox" name="constraint" value="${x}"> ${x}</label>`).join('')}</div><label>预期结果</label><textarea name="expected"></textarea><label class="ai-option"><input type="checkbox" name="ai-optimize"> 使用 AI 优化任务书</label><p class="ai-hint">未勾选时仍完全在本地生成。勾选后会打开 AI 设置页并发送清理后的任务书。</p>`}</main><footer class="actions">${preview?'<button class="secondary" data-action="back">返回修改</button><button class="secondary" data-action="json">复制 JSON</button><button class="secondary" data-action="download">下载 MD</button><button class="primary" data-action="copy">复制任务书</button>':'<button class="secondary" data-action="undo">撤销</button><button class="secondary" data-action="clear">清空选择</button><button class="primary" data-action="generate">生成任务书</button>'}</footer>`;root.append(panel);applyPanelPosition()}
  function escapeHtml(s:string){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!))}
  function ensureCompactFormUi(){const body=root.querySelector<HTMLElement>('.body');if(!body||preview)return;const request=body.querySelector<HTMLTextAreaElement>('[name=request]');if(request)request.value=formState.request;const expected=body.querySelector<HTMLTextAreaElement>('[name=expected]');if(expected){const label=expected.previousElementSibling;if(label?.tagName==='LABEL')label.remove();expected.remove()}const code=body.querySelector<HTMLTextAreaElement>('[name=code]');if(code&&!body.querySelector('[data-section=code]')){const row=code.previousElementSibling as HTMLElement|null;const label=row?.previousElementSibling;const details=document.createElement('details');details.className='form-section';details.dataset.section='code';details.innerHTML='<summary><span>相关代码</span><span class="section-summary" data-code-count></span></summary><div class="section-content"></div>';label?.before(details);const content=details.querySelector('.section-content')!;if(row)content.append(row);content.append(code);label?.remove()}const checks=body.querySelector<HTMLElement>('.checks');if(checks&&!body.querySelector('[data-section=constraints]')){const label=checks.previousElementSibling;const details=document.createElement('details');details.className='form-section';details.dataset.section='constraints';details.innerHTML='<summary><span>修改约束</span><span class="section-summary" data-constraint-count></span></summary><div class="section-content"></div>';label?.before(details);details.querySelector('.section-content')!.append(checks);label?.remove()}const codeDetails=body.querySelector<HTMLDetailsElement>('[data-section=code]');if(codeDetails)codeDetails.open=formState.codeOpen;const constraintDetails=body.querySelector<HTMLDetailsElement>('[data-section=constraints]');if(constraintDetails)constraintDetails.open=formState.constraintsOpen;const codeInput=body.querySelector<HTMLTextAreaElement>('[name=code]');if(codeInput)codeInput.value=formState.code;const languageInput=body.querySelector<HTMLSelectElement>('[name=language]');if(languageInput)languageInput.value=formState.language;body.querySelectorAll<HTMLInputElement>('[name=constraint]').forEach(input=>input.checked=formState.constraints.includes(input.value));const ai=body.querySelector<HTMLInputElement>('[name=ai-optimize]');if(ai)ai.checked=formState.aiOptimize;updateSectionSummaries()}
  function updateSectionSummaries(){const set=(element:HTMLElement|null,value:string)=>{if(element&&element.textContent!==value)element.textContent=value};set(root.querySelector<HTMLElement>('.count'),`${formState.code.length} chars`);set(root.querySelector<HTMLElement>('[data-code-count]'),formState.code?`${formState.code.length} 字符`:'可选');set(root.querySelector<HTMLElement>('[data-constraint-count]'),`已选 ${formState.constraints.length} 项`)}
  function renderScreenshotSlot(){const slot=root.querySelector<HTMLElement>('.screenshot-slot');if(!slot)return;slot.innerHTML=screenshot?`<img class="screenshot-preview" src="${screenshot.url}" alt="页面区域截图"><div class="screenshot-meta">${screenshot.width} × ${screenshot.height} · PNG</div><div class="screenshot-actions"><button class="secondary" data-action="copy-png">复制 PNG</button><button class="secondary" data-action="download-png">下载 PNG</button><button class="secondary danger" data-action="delete-screenshot">删除</button></div><label class="screenshot-note-label" for="patchbrief-screenshot-note">截图说明</label><textarea id="patchbrief-screenshot-note" name="screenshot-note" placeholder="说明截图中希望修改的位置或问题">${escapeHtml(formState.screenshotNote)}</textarea>${screenshotMessage?`<div class="screenshot-message">${escapeHtml(screenshotMessage)}</div>`:''}`:(screenshotMessage?`<div class="screenshot-message">${escapeHtml(screenshotMessage)}</div>`:'<div class="screenshot-empty">截图仅保存在当前页面内存中，不会上传。</div>');const button=root.querySelector<HTMLElement>('[data-action=capture]');if(button)button.textContent=screenshot?'重新截图':'截取页面区域'}
  function ensureScreenshotUi(){const targets=root.querySelector('.targets');if(!targets||root.querySelector('.screenshot-tool'))return;const section=document.createElement('section');section.className='screenshot-tool';section.innerHTML='<div class="screenshot-heading"><b>页面截图</b><button class="secondary" data-action="capture">截取页面区域</button></div><div class="screenshot-slot"></div>';targets.before(section);renderScreenshotSlot()}
  function ensurePublicBrand(){const brand=root.querySelector<HTMLElement>('.brand');if(brand&&brand.textContent!==BRAND_NAME)brand.textContent=BRAND_NAME}
  const panelObserver=new MutationObserver(()=>{ensurePublicBrand();ensureScreenshotUi();ensureCompactFormUi()});panelObserver.observe(root,{childList:true,subtree:true});
  const nextFrame=()=>new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));
  async function startCapture(){if(capturing)return;capturing=true;screenshotMessage='';let video:HTMLVideoElement|undefined;const displays={host:host.style.display,hover:hover.style.display,layers:selectedLayers.map(x=>x.style.display)};try{captureStream=await requestDisplayStream();video=await prepareCaptureVideo(captureStream);host.style.display='none';hover.style.display='none';selectedLayers.forEach(x=>x.style.display='none');activeCapture=selectCaptureRect();const rect=await activeCapture.promise;activeCapture=null;if(!rect){screenshotMessage='已取消截图，原有内容没有变化。';return}await nextFrame();await nextFrame();const blob=await captureVideoRegion(video,rect);if(screenshot)URL.revokeObjectURL(screenshot.url);const filename=`spotbrief-screenshot-${Date.now()}.png`;formState.screenshotNote='';screenshot={blob,url:URL.createObjectURL(blob),filename,width:Math.round(rect.width),height:Math.round(rect.height)};screenshotMessage='截图已加入任务书。'}catch(error){const name=(error as DOMException)?.name;screenshotMessage=name==='AbortError'?'已取消浏览器的截图授权，原有内容没有变化。':(error instanceof Error?error.message:'截图失败，请重试。')}finally{captureStream?.getTracks().forEach(track=>track.stop());captureStream=undefined;video?.remove();host.style.display=displays.host;hover.style.display=displays.hover;selectedLayers.forEach((x,i)=>x.style.display=displays.layers[i]||'');capturing=false;renderScreenshotSlot()}}
  async function copyScreenshot(){if(!screenshot)return;try{if(!navigator.clipboard?.write||typeof ClipboardItem==='undefined')throw new Error('当前浏览器不支持直接复制图片');await navigator.clipboard.write([new ClipboardItem({'image/png':screenshot.blob})]);screenshotMessage='PNG 已复制到剪贴板。'}catch{screenshotMessage='无法复制 PNG，请使用“下载 PNG”。'}renderScreenshotSlot()}
  function downloadScreenshot(){if(!screenshot)return;const anchor=document.createElement('a');anchor.href=screenshot.url;anchor.download=screenshot.filename;anchor.click();screenshotMessage='PNG 下载已开始。';renderScreenshotSlot()}
  function deleteScreenshot(){if(!screenshot)return;URL.revokeObjectURL(screenshot.url);screenshot=undefined;formState.screenshotNote='';screenshotMessage='截图已删除。';renderScreenshotSlot()}
  function move(e:PointerEvent){if(capturing||paused||e.composedPath().includes(host))return;last=(e.composedPath().find(x=>x instanceof Element&&!x.closest?.('[data-patchbrief-ui]')) as Element)||null;if(!raf)raf=requestAnimationFrame(()=>{raf=0;positionOverlay(hover,last)})}
  function click(e:MouseEvent){if(capturing||paused||e.composedPath().includes(host))return;const el=resolveTarget((e.composedPath().find(x=>x instanceof Element&&!x.closest?.('[data-patchbrief-ui]')) as Element));if(!el)return;e.preventDefault();e.stopImmediatePropagation();save();const at=selections.findIndex(x=>x.element===el);if(e.shiftKey){if(at>=0)selections.splice(at,1);else selections.push(record(el))}else selections=at>=0?[]:[record(el)];render()}
  const reposition=()=>selections.forEach((s,i)=>{const layer=selectedLayers[i];if(layer)positionOverlay(layer,s.element)});const resize=()=>{reposition();applyPanelPosition()};document.addEventListener('pointermove',move,true);document.addEventListener('click',click,true);window.addEventListener('scroll',reposition,true);window.addEventListener('resize',resize);
  root.addEventListener('pointerdown',event=>{const e=event as PointerEvent;if(innerWidth<=620||e.button!==0)return;const target=e.target as Element;const top=target.closest<HTMLElement>('.top');if(!top||target.closest('button,input,textarea,select,a'))return;const panel=root.querySelector<HTMLElement>('.panel');if(!panel)return;const rect=panel.getBoundingClientRect();drag={pointerId:e.pointerId,offsetX:e.clientX-rect.left,offsetY:e.clientY-rect.top,handle:top};top.setPointerCapture?.(e.pointerId);top.classList.add('dragging');e.preventDefault()});
  const dragMove=(e:PointerEvent)=>{if(!drag||e.pointerId!==drag.pointerId)return;const panel=root.querySelector<HTMLElement>('.panel');if(!panel)return;const bounded=clampPanelPosition({x:e.clientX-drag.offsetX,y:e.clientY-drag.offsetY},{width:innerWidth,height:innerHeight},{width:panel.offsetWidth,height:panel.offsetHeight});preferences.panelPosition=bounded;panel.style.left=`${bounded.x}px`;panel.style.top=`${bounded.y}px`;panel.style.right='auto'};
  const dragEnd=(e:PointerEvent)=>{if(!drag||e.pointerId!==drag.pointerId)return;drag.handle.classList.remove('dragging');drag.handle.releasePointerCapture?.(e.pointerId);drag=null;savePreferences(preferences)};window.addEventListener('pointermove',dragMove,true);window.addEventListener('pointerup',dragEnd,true);window.addEventListener('pointercancel',dragEnd,true);
  root.addEventListener('input',e=>{const x=e.target as HTMLTextAreaElement;if(x.dataset.note!==undefined)selections[Number(x.dataset.note)]!.note=x.value;if(x.name==='request')formState.request=x.value;if(x.name==='code')formState.code=x.value;if(x.name==='screenshot-note')formState.screenshotNote=x.value;updateSectionSummaries()});
  root.addEventListener('change',e=>{const x=e.target as HTMLInputElement|HTMLSelectElement;if(x.name==='language')formState.language=x.value;if(x.name==='constraint')formState.constraints=[...root.querySelectorAll<HTMLInputElement>('[name=constraint]:checked')].map(input=>input.value);if(x.name==='ai-optimize')formState.aiOptimize=(x as HTMLInputElement).checked;updateSectionSummaries()});
  root.addEventListener('toggle',e=>{const details=e.target as HTMLDetailsElement;if(details.dataset.section==='code')formState.codeOpen=details.open;if(details.dataset.section==='constraints')formState.constraintsOpen=details.open},true);
  root.addEventListener('click',async e=>{const b=(e.target as Element).closest<HTMLElement>('[data-action],[data-remove]');if(!b)return;if(b.dataset.remove){save();selections.splice(Number(b.dataset.remove),1);render();return}switch(b.dataset.action){case'reset-position':delete preferences.panelPosition;savePreferences(preferences);applyPanelPosition();break;case'pause':paused=!paused;hover.style.display='none';render();break;case'collapse':collapsed=!collapsed;preferences.collapsed=collapsed;savePreferences(preferences);render();break;case'close':controller.destroy();break;case'clear':save();selections=[];render();break;case'undo':selections=history.pop()||selections;render();break;case'capture':await startCapture();break;case'copy-png':await copyScreenshot();break;case'download-png':downloadScreenshot();break;case'delete-screenshot':deleteScreenshot();break;case'clear-code':formState.code='';{const code=root.querySelector<HTMLTextAreaElement>('[name=code]');if(code)code.value=''}updateSectionSummaries();break;case'generate':await generate();break;case'back':preview='';render();break;case'copy':await copyText(preview);break;case'json':await copyText(serializeBriefJson(draft()));break;case'download':downloadText(preview,`spotbrief-${Date.now()}.md`);break}});
  const key=(e:KeyboardEvent)=>{if(capturing)return;if((e.target as Element)?.matches?.('input,textarea,select,[contenteditable=true]'))return;if((e.metaKey||e.ctrlKey)&&e.key==='z'){e.preventDefault();selections=history.pop()||selections;render()}else if((e.metaKey||e.ctrlKey)&&e.key==='Enter'){e.preventDefault();void generate()}else if(e.key==='Escape'){if(selections.length){save();selections=[]}else paused=!paused;render()}};document.addEventListener('keydown',key,true);
  const controller={version:VERSION,open(){host.style.display='';collapsed=false;render()},pause(){paused=true;render()},resume(){paused=false;render()},destroy(){activeCapture?.cancel();captureStream?.getTracks().forEach(track=>track.stop());if(screenshot)URL.revokeObjectURL(screenshot.url);panelObserver.disconnect();document.removeEventListener('pointermove',move,true);document.removeEventListener('click',click,true);document.removeEventListener('keydown',key,true);window.removeEventListener('scroll',reposition,true);window.removeEventListener('resize',resize);window.removeEventListener('pointermove',dragMove,true);window.removeEventListener('pointerup',dragEnd,true);window.removeEventListener('pointercancel',dragEnd,true);cancelAnimationFrame(raf);hover.remove();selectedLayers.forEach(x=>x.remove());document.querySelector('.patchbrief-capture-layer')?.remove();host.remove();delete window.__PATCHBRIEF__}};window.__PATCHBRIEF__=controller;render();
})();
